import matplotlib.pyplot as plt
import swiftascmaps
import seaborn as sns
sns.set(style="white")

symlog_variables = [
    'v_sphere_r',
    'momentum_sphere_r',
    'v_cyl_z',
    'grav_crpfz',
    'grav_therpfz',
    'grav_therpfrsphere',
    'grav_crpfrsphere',
    'grav_totpfrsphere',
    'grav_magpfrsphere',
    'grad_crpz',
    'grad_crprsphere',
    'grav_gz',
    'grav_frsphere',
    'ang_momentum_x',
    'ang_momentum_y',
    'ang_momentum_z',
    'massflow_rate_sphere_r',
    'net_cooling',
    'Bx_proj',
    'By_proj',
    'Bz_proj'
]

plotting_dictionary = dict(
    density = {'cmap': sns.color_palette("mako", as_cmap=True),
                'text_over':'white',
                'label':r'$\rho$ [g/cm$^{3}$]',
                'label_log':r'$\log\left(\rho/{\rm g\,cm}^{-3}\right)$',
                'units':'g*cm**-3',
                'vmin':8e-31,
                'vmax':7e-22,
                'bin_min':1e-30,
                'bin_max':8e-20,
                'vmin_galaxy':8e-28,
                'vmax_galaxy':5e-21,
                'vmin_outflow':8e-28,
                'vmax_outflow':5e-21,
                'vmin_cgm':5e-28,
                'vmax_cgm':8e-24,
                'vmin_cluster':8e-31,
                'vmax_cluster':7e-22,
    },
    mass = {'cmap':sns.color_palette("mako", as_cmap=True),
            'text_over':'white',
            'label':r'$M_{\rm gas}$ [M$_{\odot}$]',
            'label_log':r'$\log$(\frac{M_{\rm gas}}{{\rm M}$_{\odot}$})',
            'units':'Msun',
            'vmin':1,
            'vmax':1e+8,
            'bin_min':1,
            'bin_max':1e+8,
            'vmin_galaxy':1e+3,
            'vmax_galaxy':1e+8
    },
    temperature = {'cmap':sns.color_palette("rocket", as_cmap=True),
                    'text_over':'white',
                    'label':r'$T$ [K]',
                    'label_log':r'$\log\left(T/{\rm K}\right)$',
                    'units':'K',
                    'vmin':8e+3,
                    'vmax':2e+8,
                    'bin_min':2,
                    'bin_max':2e+8,
                    'vmin_galaxy':8e+2,
                    'vmax_galaxy':8e+6,
                    'vmin_outflow':4e+3,
                    'vmax_outflow':7e+5,
                    'vmin_cgm':7e+3,
                    'vmax_cgm':8e+6
    },
    thermal_energy = {'cmap':sns.color_palette("rocket", as_cmap=True),
                            'text_over':'white',
                            'label':r'$E_{\rm ther}$ [erg]',
                            'label_log':r'$\log(\frac{E_{\rm ther}}{{\rm erg}})$',
                            'units':'erg',
                            'vmin':5e+1,
                            'vmax':2e+6,
                            'bin_min':5e+1,
                            'bin_max':2e+6,
                            'vmin_galaxy':5e+3,
                            'vmax_galaxy':8e+6
    },
    thermal_pressure = {'cmap':'viridis',
                            'text_over':'white',
                            'label':r'$P_{\rm ther}$ [erg/cm$^{-3}$]',
                            'label_log':r'$\log\left(\frac{P_{\rm ther}}{{\rm erg/cm}^{-3}}\right)$',
                            'units':'erg*cm**-3',
                            'vmin':3e-15,
                            'vmax':8e-9,
                            'bin_min':3e-15,
                            'bin_max':8e-9,
                            'vmin_galaxy':3e-15,
                            'vmax_galaxy':8e-9
    },
    thermal_energy_specific = {'cmap':sns.color_palette("rocket", as_cmap=True),
                                'text_over':'white',
                                'label':r'$\epsilon_{\rm ther}$ [erg/g]',
                                'label_log':r'$\log(\frac{\epsilon_{\rm ther}}{{\rm erg/g}})$',
                                'units':'erg*g**-1',
                                'vmin':5e+1,
                                'vmax':2e+6,
                                'bin_min':5e+9,
                                'bin_max':2e+13,
                                'vmin_galaxy':5e+3,
                                'vmax_galaxy':8e+6
    },
    net_cooling = {'cmap':'vlag',
                        'text_over':'black',
                        'label':r'$\Lambda_{\rm cool}$ [erg/(s cm$^{3}$)]',
                        'label_log':r'$\log\left(\frac{\Lambda_{\rm cool}}{{\rm erg/(s cm}^{3})}\right)$',
                        'units':'erg*s**-1*cm**-3',
                        'vmin':-1e-26,
                        'vmax':1e-21,
                        'bin_min':-1e-18,
                        'bin_max':1e-10,
                        'vmin_galaxy':-1e-26,
                        'vmax_galaxy':2e-21,
                        'vmin_cgm':-1e-28,
                        'vmax_cgm':1e-26,
                        'linthresh':1e-30,
                        'linscale':1
    },
    stheatcooling_ratio = {'cmap':'Spectral',
                        'text_over':'black',
                        'label':r'$\vert \Lambda_{\rm st} / \Lambda_{\rm cool} \vert$',
                        'label_log':r'$\log(\Lambda_{\rm st}/\Lambda_{\rm cool})$',
                        'units':'dimensionless',
                        'vmin':1e-6,
                        'vmax':1,
                        'bin_min':1e-10,
                        'bin_max':200,
                        'vmin_galaxy':1e-4,
                        'vmax_galaxy':200,
                        'vmin_cgm':1e-4,
                        'vmax_cgm':2000
    },
    entropy_specific = {'cmap':'plasma',
                        'text_over':'white',
                        'label':r'$s$ [erg/(g K)]',
                        'label_log':r'$\log(\frac{s}{{\rm erg/(g K)}})$',
                        'units':'erg*K**-1*g**-1',
                        'vmin':8e+3,
                        'vmax':2e+5,
                        'bin_min':8e+3,
                        'bin_max':2e+5,
                        'vmin_galaxy':8e+7,
                        'vmax_galaxy':2e+9
    },
    metallicity = {'cmap':'swift.red_tv',
                    'text_over':'white',
                    'label':r'$Z$ [$Z_{\odot}$]',
                    'label_log':r'$\log\left(Z/{\rm Z}_{\odot}\right)$',
                    'units':'dimensionless',
                    'vmin':5e-3,
                    'vmax':1.5,
                    'bin_min':2e-4,
                    'bin_max':2.0,
                    'vmin_galaxy':6e-2,
                    'vmax_galaxy':1.5,
                    'vmin_cgm':5e-3,
                    'vmax_cgm':1.5,
                    'vmin_outflow':5e-3,
                    'vmax_outflow':1.5
    },
    magnetic_energy = {'cmap':'inferno',
                                'text_over':'white',
                                'label':r'$E_{\rm mag}$ [erg]',
                                'label_log':r'$\log(\frac{E_{\rm mag}}{{\rm erg}})$',
                                'units':'erg',
                                'vmin':5e+10,
                                'vmax':3e+12,
                                'bin_min':5e+10,
                                'bin_max':3e+12,
                                'vmin_cgm':5e+51,
                                'vmax_cgm':3e+55

    },
    magnetic_energy_specific = {'cmap':sns.cubehelix_palette(reverse=True,as_cmap=True),
                                'text_over':'white',
                                'label':r'$\epsilon_{\rm mag}$ [erg/g]',
                                'label_log':r'$\log(\frac{\epsilon_{\rm mag}}{{\rm erg/g}})$',
                                'units':'erg*g**-1',
                                'vmin':5e+7,
                                'vmax':3e+11,
                                'bin_min':2e+4,
                                'bin_max':3e+10,
                                'vmin_galaxy':5e+7,
                                'vmax_galaxy':3e+11,
                                'vmin_cgm':5e+7,
                                'vmax_cgm':3e+11

    },
    magnetic_energy_density = {'cmap':'inferno',
                                'text_over':'white',
                                'label':r'$\varepsilon_{\rm mag}$ [erg/cm$^{3}$]',
                                'label_log':r'$\log(\frac{\varepsilon_{\rm mag}}{{\rm erg/cm}^{3}})$',
                                'units':'erg*cm**-3',
                                'vmin':4e-17,
                                'vmax':5e-11,
                                'bin_min':4e-17,
                                'bin_max':5e-11,
                                'vmin_galaxy':4e-17,
                                'vmax_galaxy':5e-11

    },
    magnetic_magnitude = {'cmap':'inferno',
                                'text_over':'white',
                                'label':r'$B$ [$G$]',
                                'label_log':r'$\log(B/{\rm G})$',
                                'units':'G',
                                'vmin':4e-12,
                                'vmax':5e-5,
                                'bin_min':4e-12,
                                'bin_max':5e-5,
                                'vmin_galaxy':4e-10,
                                'vmax_galaxy':5e-5,
                                'vmin_cgm':4e-10,
                                'vmax_cgm':5e-7,
                                'vmin_outflow':4e-10,
                                'vmax_outflow':5e-7

    },
    Bx_proj = {'cmap':sns.color_palette("icefire", as_cmap=True),
                                'text_over':'white',
                                'label':r'$B_x$ [$G$]',
                                'label_log':r'$\log(B_x/{\rm G})$',
                                'units':'G',
                                'vmin':4e-12,
                                'vmax':5e-5,
                                'bin_min':4e-12,
                                'bin_max':5e-5,
                                'vmin_galaxy':-5e-6,
                                'vmax_galaxy':5e-6,
                                'vmin_cgm':4e-10,
                                'vmax_cgm':5e-7,
                                'linthresh':1e-8,
                                'linscale':1e-9

    },
    By_proj = {'cmap':sns.color_palette("icefire", as_cmap=True),
                                'text_over':'white',
                                'label':r'$B_y$ [$G$]',
                                'label_log':r'$\log(B_y/{\rm G})$',
                                'units':'G',
                                'vmin':4e-12,
                                'vmax':5e-5,
                                'bin_min':4e-12,
                                'bin_max':5e-5,
                                'vmin_galaxy':-5e-6,
                                'vmax_galaxy':5e-6,
                                'vmin_cgm':4e-10,
                                'vmax_cgm':5e-7,
                                'linthresh':1e-8,
                                'linscale':1e-9

    },
    Bz_proj = {'cmap':sns.color_palette("icefire", as_cmap=True),
                                'text_over':'white',
                                'label':r'$B_z$ [$G$]',
                                'label_log':r'$\log(B_z/{\rm G})$',
                                'units':'G',
                                'vmin':4e-12,
                                'vmax':5e-5,
                                'bin_min':4e-12,
                                'bin_max':5e-5,
                                'vmin_galaxy':-5e-6,
                                'vmax_galaxy':5e-6,
                                'vmin_cgm':4e-10,
                                'vmax_cgm':5e-7,
                                'linthresh':1e-8,
                                'linscale':1e-9

    },
    alfven_speed = {'cmap':'swift.evermore',
                        'text_over':'white',
                        'label':r'$v_{\rm A}$ [${\rm km s}^{-1}$]',
                        'label_log':r'$\log(\frac{v_{\rm A}}{{\rm km s}^{-1}})$',
                        'units':'km/s',
                        'vmin':3e-2,
                        'vmax':5e0,
                        'bin_min':3e-2,
                        'bin_max':5e0,
                        'vmin_galaxy':0.01,
                        'vmax_galaxy':30,
                        'vmin_cgm':3e-2,
                        'vmax_cgm':5e0,

    },
    diffusion_speed = {'cmap':'swift.red',
                                'text_over':'white',
                                'label':r'$v_{\rm Diff}$ [km s$^{-1}$]',
                                'label_log':r'$\log(\frac{v_{\rm Diff}}{{\rm km s}^{-1}})$',
                                'units':'km/s',
                                'vmin':3e-2,
                                'vmax':200,
                                'bin_min':3e-2,
                                'bin_max':500,
                                'vmin_galaxy':3e-1,
                                'vmax_galaxy':150

    },
    alfvendiff_ratio = {'cmap':'swift.red',
                                'text_over':'white',
                                'label':r'$v_{\rm st}/(v_{\rm Diff}+v_{\rm st})$',
                                'label_log':r'$\log \left(\frac{v_{\rm st}}{v_{\rm st}+v_{\rm Diff}}\right)$',
                                'units':'dimensionless',
                                'vmin':3e-2,
                                'vmax':1,
                                'bin_min':3e-2,
                                'bin_max':5e0,
                                'vmin_galaxy':3e-2,
                                'vmax_galaxy':1,
                                'vmin_cgm':5e-2,
                                'vmax_cgm':1

    },
    cr_energy = {'cmap':sns.cubehelix_palette(start=2, rot=0, dark=0, light=.95, reverse=True, as_cmap=True),
                        'text_over':'white',
                        'label':r'$E_{\rm CR}$ [erg]',
                        'label_log':r'$\log(\frac{\varepsilon_{\rm CR}}{{\rm erg/cm}^{3}})$',
                        'label_log':r'$\log(\frac{E_{\rm CR}}{{\rm erg}})$',
                        'units':'erg',
                        'vmin':4e-14,
                        'vmax':8e-11,
                        'bin_min':4e-14,
                        'bin_max':8e-11,
                        'vmin_galaxy':4e48,
                        'vmax_galaxy':8e53,
                        'vmin_cgm':2e55,
                        'vmax_cgm':8e57

    },
    cr_energy_density = {'cmap':'YlGnBu_r',#sns.cubehelix_palette(start=2, rot=0, dark=0, light=.95, reverse=False, as_cmap=True),
                        'text_over':'black',
                        'label':r'$\varepsilon_{\rm CR}$ [erg/cm$^{3}$]',
                        'label_log':r'$\log(\frac{\varepsilon_{\rm CR}}{{\rm erg/cm}^{3}})$',
                        'units':'erg*cm**-3',
                        'vmin':7e-18,
                        'vmax':3e-11,
                        'bin_min':7e-18,
                        'bin_max':8e-12,
                        'vmin_galaxy':6e-13,
                        'vmax_galaxy':5e-9,
                        'vmin_cgm':7e-16,
                        'vmax_cgm':3e-11,

    },
    cr_temperature_eff = {'cmap':'YlGnBu_r',#sns.cubehelix_palette(start=2, rot=0, dark=0, light=.95, reverse=False, as_cmap=True),
                        'text_over':'black',
                        'label':r'$T_{\rm CR,eff}$ [erg/cm$^{3}$]',
                        'label_log':r'$\log\left(\frac{T_{\rm CR,eff}}{{\rm K}}\right)$',
                        'units':'K',
                        'vmin':2e+4,
                        'vmax':8e+6,
                        'bin_min':2e+4,
                        'bin_max':8e+6,
                        'vmin_galaxy':8e+1,
                        'vmax_galaxy':8e+6,
                        'vmin_outflow':5e+3,
                        'vmax_outflow':3e+5

    },
    cr_pressure = {'cmap':'YlGnBu_r',#sns.cubehelix_palette(start=2, rot=0, dark=0, light=.95, reverse=False, as_cmap=True),
                        'text_over':'black',
                        'label':r'$P_{\rm CR}$ [erg/cm$^{3}$]',
                        'label_log':r'$\log(\frac{P_{\rm CR}}{{\rm erg/cm}^{3}})$',
                        'units':'erg*cm**-3',
                        'vmin':7e-18,
                        'vmax':8e-12,
                        'bin_min':7e-18,
                        'bin_max':8e-12,
                        'vmin_grad':7e-16,
                        'vmax_grad':8e-13,
                        'vmin_galaxy':6e-14,
                        'vmax_galaxy':2e-10

    },
    gamma_ray_luminosity = {'cmap':'swift.speak_now_tv',
                                'text_over':'white',
                                'label':r'$L_{\gamma}$ [erg/(cm$^{2}$s)]',
                                'label_log':r'$\log(\frac{L_{\gamma}}{{\rm erg}/({\rm cm}^{2}{\rm s})})$',
                                'units':'erg*cm**-2*s**-1',
                                'vmin':1e-8,
                                'vmax':1e-4,
                                'bin_min':1e-8,
                                'bin_max':1e-4,
                                'vmin_galaxy':8e-8,
                                'vmax_galaxy':7e-3

    },
    gradscale_crprsphere = {'cmap':sns.cubehelix_palette(start=.5, rot=-.75, as_cmap=True),
                        'text_over':'white',
                        'label':r'$\vert P_{\rm CR}/\nabla P_{\rm CR}\vert$ [kpc]',
                        'label_log':r'$\log(\frac{\vert P_{\rm CR}/\nabla P_{\rm CR}\vert}{\rm kpc})$',
                        'units':'kpc',
                        'vmin':1e-3,
                        'vmax':1e3,
                        'bin_min':1e-3,
                        'bin_max':1e3,
                        'vmin_galaxy':3e-2,
                        'vmax_galaxy':3e1

    },
    gradscale_crp = {'cmap':sns.cubehelix_palette(start=.5, rot=-.75, as_cmap=True),
                        'text_over':'white',
                        'label':r'$\vert P_{\rm CR}/\nabla P_{\rm CR}\vert$ [kpc]',
                        'label_log':r'$\log(\frac{\vert P_{\rm CR}/\nabla P_{\rm CR}\vert}{\rm kpc})$',
                        'units':'kpc',
                        'vmin':1e-3,
                        'vmax':1e3,
                        'bin_min':1e-3,
                        'bin_max':1e3,
                        'vmin_galaxy':3e-2,
                        'vmax_galaxy':3e1

    },
    grad_crpz = {'cmap':sns.color_palette("vlag", as_cmap=True),
                        'text_over':'black',
                        'label':r'$\nabla_z P_{\rm CR}$ [erg/cm$^{4}$]',
                        'label_log':r'$\log(\frac{\nabla_z P_{\rm CR}}{{\rm erg/cm}^{4}})$',
                        'units':'erg*cm**-4',
                        'vmin':-2e-31,
                        'vmax':2e-31,
                        'bin_min':-2e-31,
                        'bin_max':2e-31,
                        'vmin_galaxy':-2e-28,
                        'vmax_galaxy':2e-28

    },
    grad_crprsphere = {'cmap':sns.color_palette("vlag", as_cmap=True),
                        'text_over':'black',
                        'label':r'$\nabla_r P_{\rm CR}$ [erg/cm$^{4}$]',
                        'label_log':r'$\log(\frac{\nabla_r P_{\rm CR}}{{\rm erg/cm}^{4}})$',
                        'units':'erg*cm**-4',
                        'vmin':-2e-31,
                        'vmax':2e-31,
                        'bin_min':-2e-31,
                        'bin_max':2e-31,
                        'vmin_galaxy':-2e-29,
                        'vmax_galaxy':2e-29,
                        'linthresh':1e-34,
                        'linscale':1e-33

    },
    grad_crp = {'cmap':sns.color_palette("vlag", as_cmap=True),
                        'text_over':'black',
                        'label':r'$\vert\nabla P_{\rm CR}\vert$ [erg/cm$^{4}$]',
                        'label_log':r'$\log(\vert\frac{\nabla P_{\rm CR}\vert}{{\rm erg/cm}^{4}})$',
                        'units':'erg*cm**-4',
                        'vmin':8e-36,
                        'vmax':2e-31,
                        'bin_min':8e-36,
                        'bin_max':2e-31,
                        'vmin_galaxy':8e-36,
                        'vmax_galaxy':2e-28

    },
    grad_crp_dotmag = {'cmap':'gnuplot',
                        'text_over':'white',
                        'label':r'$\nabla P_{\rm CR} \cdot \vec{b}$ [erg/cm$^{4}$]',
                        'label_log':r'$\log(\frac{\nabla P_{\rm CR} \cdot \vec{b}}{{\rm erg/cm}^{4}})$',
                        'units':'erg*cm**-4',
                        'vmin':2e-37,
                        'vmax':2e-31,
                        'bin_min':2e-37,
                        'bin_max':2e-31,
                        'vmin_galaxy':8e-36,
                        'vmax_galaxy':4e-31

    },
    grad_thermalpressure = {'cmap':sns.color_palette("vlag", as_cmap=True),
                        'text_over':'black',
                        'label':r'$\vert\nabla P_{\rm ther}\vert$ [erg/cm$^{4}$]',
                        'label_log':r'$\log(\vert\frac{\nabla P_{\rm ther}\vert}{{\rm erg/cm}^{4}})$',
                        'units':'erg*cm**-4',
                        'vmin':-2e-31,
                        'vmax':2e-31,
                        'bin_min':-2e-31,
                        'bin_max':2e-31,
                        'vmin_galaxy':-2e-28,
                        'vmax_galaxy':2e-28

    },
    streaming_heating = {'cmap':'gnuplot',
                        'text_over':'white',
                        'label':r'$\Lambda_{\rm st}$ [erg/(s cm$^{3})$]',
                        'label_log':r'$\log(\frac{\Lambda_{\rm st}}{{\rm erg/(s cm}^{3})})$',
                        'units':'erg*s**-1*cm**-3',
                        'vmin':3e-33,
                        'vmax':1e-23,
                        'bin_min':3e-33,
                        'bin_max':1e-23,
                        'vmin_galaxy':3e-33, 
                        'vmax_galaxy':1e-23,

    },
    cr_GH08heat = {'cmap':'gnuplot',
                        'text_over':'white',
                        'label':r'$\Lambda_{\rm HC}$ [erg/(s cm$^{3})$]',
                        'label_log':r'$\log(\frac{\Lambda_{\rm HC}}{{\rm erg/(s cm}^{3})})$',
                        'units':'erg*s**-1*cm**-3',
                        'vmin':3e-33,
                        'vmax':1e-23,
                        'bin_min':3e-33,
                        'bin_max':1e-23,
                        'vmin_galaxy':3e-33, 
                        'vmax_galaxy':2e-21,

    },
    cr_energy_specific = {'cmap':sns.color_palette("crest_r", as_cmap=True), #sns.cubehelix_palette(start=2, rot=0, dark=0, light=.95, reverse=True, as_cmap=True),
                                'text_over':'white',
                                'label':r'$\epsilon_{\rm CR}$ [erg/g]',
                                'label_log':r'$\log(\frac{\epsilon_{\rm CR}}{\rm erg/g})$',
                                'units':'erg*g**-1',
                                'vmin':7e+11,
                                'vmax':7e+14,
                                'bin_min':1e+9,
                                'bin_max':1e+17,
                                'vmin_galaxy':5e+15,
                                'vmax_galaxy':7e+16,
                                'vmin_cgm':5e+12,
                                'vmax_cgm':7e+14

    },
    total_coolingtime = {'cmap':'swift.red',
                                'text_over':'white',
                                'label':r'$t_{\rm cool}$ [Myr]',
                                'label_log':r'$\log(\frac{t_{\rm cool}}{\rm Myr})$',
                                'units':'Myr',
                                'vmin':1e-2,
                                'vmax':7e+5,
                                'bin_min':1e-2,
                                'bin_max':7e+5,
                                'vmin_galaxy':1e-2,
                                'vmax_galaxy':7e+5

    },
    crthermal_ratio = {'cmap':sns.color_palette("vlag", as_cmap=True),
                        'text_over':'black',
                        'label':r'$\frac{\nabla P_{\rm CR}}{\nabla P_{\rm ther}}$',
                        'label_log':r'$\log(\frac{\nabla P_{\rm CR}}{\nabla P_{\rm ther}})$',
                        'units':'dimensionless',
                        'vmin':7e-18,
                        'vmax':8e-12,
                        'bin_min':7e-18,
                        'bin_max':8e-12,
                        'vmin_galaxy':1e-3,
                        'vmax_galaxy':1e+2

    },
    grav_crpfz = {'cmap':sns.color_palette("vlag", as_cmap=True),
                        'text_over':'black',
                        'label':r'$\frac{-\nabla_{z} P_{\rm CR}}{\rho g_{z}}$',
                        'label_log':r'$\log(\frac{-\nabla_{z} P_{\rm CR}}{\rho g_{z}})$',
                        'units':'dimensionless',
                        'vmin':-100,
                        'vmax':+100,
                        'bin_min':-100,
                        'bin_max':+100,
                        'vmin_galaxy':-5,
                        'vmax_galaxy':+5,
                        'linthresh':1e-2,
                        'linscale':1e-2

    },
    grav_therpfz = {'cmap':sns.color_palette("vlag", as_cmap=True),
                        'text_over':'black',
                        'label':r'$\frac{-\nabla_{z} P_{\rm ther}}{\rho g_{z}}$',
                        'label_log':r'$\log(\frac{-\nabla_{z} P_{\rm ther}}{\rho g_{z}})$',
                        'units':'dimensionless',
                        'vmin':-100,
                        'vmax':+100,
                        'bin_min':-100,
                        'bin_max':+100,
                        'vmin_galaxy':-5,
                        'vmax_galaxy':+5,
                        'linthresh':1e-2,
                        'linscale':1e-2

    },
    grav_crpfrsphere = {'cmap':'RdBu_r',
                        'text_over':'white',
                        'label':r'$\frac{-\nabla_{r} P_{\rm CR}}{\rho g_{r}}$',
                        'label_log':r'$\log(\frac{-\nabla_{r} P_{\rm CR}}{\rho g_{r}})$',
                        'units':'dimensionless',
                        'vmin':-100,
                        'vmax':+100,
                        'bin_min':-100,
                        'bin_max':+100,
                        'vmin_galaxy':-5,
                        'vmax_galaxy':+5,
                        'linthresh':1,
                        'linscale':1

    },
    grav_crpfrspherepos = {'cmap':'Spectral',
                        'text_over':'black',
                        'label':r'$\frac{-\nabla_{r} P_{\rm CR}}{\rho g_{r}}$',
                        'label_log':r'$\log(\frac{-\nabla_{r} P_{\rm CR}}{\rho g_{r}})$',
                        'units':'dimensionless',
                        'vmin':1e-3,
                        'vmax':+100,
                        'bin_min':1e-3,
                        'bin_max':+1000,
                        'vmin_galaxy':1e-3,
                        'vmax_galaxy':+10,

    },
    grav_crpfrsphereneg = {'cmap':'Spectral',
                        'text_over':'black',
                        'label':r'$\frac{-\nabla_{r} P_{\rm CR}}{\rho g_{r}}$',
                        'label_log':r'$\log(\frac{-\nabla_{r} P_{\rm CR}}{\rho g_{r}})$',
                        'units':'dimensionless',
                        'vmin':1e-3,
                        'vmax':+100,
                        'bin_min':1e-3,
                        'bin_max':+1000,
                        'vmin_galaxy':1e-3,
                        'vmax_galaxy':+10,

    },
    grav_therpfrsphere = {'cmap':'RdBu_r',
                        'text_over':'white',
                        'label':r'$\frac{-\nabla_{r} P_{\rm ther}}{\rho g_{r}}$',
                        'label_log':r'$\log(\frac{-\nabla_{r} P_{\rm ther}}{\rho g_{r}})$',
                        'units':'dimensionless',
                        'vmin':-100,
                        'vmax':+100,
                        'bin_min':-50,
                        'bin_max':+50,
                        'vmin_galaxy':-5,
                        'vmax_galaxy':+5,
                        'linthresh':1,
                        'linscale':1

    },
    grav_therpfrspherepos = {'cmap':'Spectral',
                        'text_over':'black',
                        'label':r'$\frac{-\nabla_{r} P_{\rm ther}}{\rho g_{r}}$',
                        'label_log':r'$\log(\frac{-\nabla_{r} P_{\rm ther}}{\rho g_{r}})$',
                        'units':'dimensionless',
                        'vmin':1e-3,
                        'vmax':+100,
                        'bin_min':1e-3,
                        'bin_max':+100,
                        'vmin_galaxy':1e-3,
                        'vmax_galaxy':+10,

    },
    grav_therpfrsphereneg = {'cmap':'Spectral',
                        'text_over':'black',
                        'label':r'$\frac{-\nabla_{r} P_{\rm ther}}{\rho g_{r}}$',
                        'label_log':r'$\log(\frac{-\nabla_{r} P_{\rm ther}}{\rho g_{r}})$',
                        'units':'dimensionless',
                        'vmin':1e-3,
                        'vmax':+100,
                        'bin_min':1e-5,
                        'bin_max':+500,
                        'vmin_galaxy':1e-3,
                        'vmax_galaxy':+10,

    },
    grav_totpfrsphere = {'cmap':sns.color_palette("vlag", as_cmap=True),
                        'text_over':'black',
                        'label':r'$\frac{-\nabla_{r} P_{\rm tot}}{\rho g_{r}}$',
                        'label_log':r'$\log(\frac{-\nabla_{r} P_{\rm tot}}{\rho g_{r}})$',
                        'units':'dimensionless',
                        'vmin':-100,
                        'vmax':+100,
                        'bin_min':-100,
                        'bin_max':+100,
                        'vmin_galaxy':-5,
                        'vmax_galaxy':+5,
                        'linthresh':1,
                        'linscale':1

    },
    grav_totpfrspherepos = {'cmap':'Spectral',
                        'text_over':'black',
                        'label':r'$\frac{-\nabla_{r} P_{\rm tot}}{\rho g_{r}}$',
                        'label_log':r'$\log(\frac{-\nabla_{r} P_{\rm tot}}{\rho g_{r}})$',
                        'units':'dimensionless',
                        'vmin':1e-3,
                        'vmax':+100,
                        'bin_min':1e-3,
                        'bin_max':+1000,
                        'vmin_galaxy':1e-3,
                        'vmax_galaxy':+10,

    },
    grav_totpfrsphereneg = {'cmap':'Spectral',
                        'text_over':'black',
                        'label':r'$\frac{-\nabla_{r} P_{\rm tot}}{\rho g_{r}}$',
                        'label_log':r'$\log(\frac{-\nabla_{r} P_{\rm tot}}{\rho g_{r}})$',
                        'units':'dimensionless',
                        'vmin':1e-3,
                        'vmax':+100,
                        'bin_min':1e-3,
                        'bin_max':+1000,
                        'vmin_galaxy':1e-3,
                        'vmax_galaxy':+10,

    },
    grav_magpfrsphere = {'cmap':sns.color_palette("vlag", as_cmap=True),
                        'text_over':'black',
                        'label':r'$\frac{-\nabla_{r} P_{\rm mag}}{\rho g_{r}}$',
                        'label_log':r'$\log(\frac{-\nabla_{r} P_{\rm mag}}{\rho g_{r}})$',
                        'units':'dimensionless',
                        'vmin':-100,
                        'vmax':+100,
                        'bin_min':-100,
                        'bin_max':+100,
                        'vmin_galaxy':-5,
                        'vmax_galaxy':+5,
                        'linthresh':1,
                        'linscale':1e-5

    },
    grav_magpfrspherepos = {'cmap':'Spectral',
                        'text_over':'black',
                        'label':r'$\frac{-\nabla_{r} P_{\rm mag}}{\rho g_{r}}$',
                        'label_log':r'$\log(\frac{-\nabla_{r} P_{\rm mag}}{\rho g_{r}})$',
                        'units':'dimensionless',
                        'vmin':1e-5,
                        'vmax':+100,
                        'bin_min':1e-5,
                        'bin_max':+10,
                        'vmin_galaxy':1e-3,
                        'vmax_galaxy':+10,

    },
    grav_magpfrsphereneg = {'cmap':'Spectral',
                        'text_over':'black',
                        'label':r'$\frac{-\nabla_{r} P_{\rm mag}}{\rho g_{r}}$',
                        'label_log':r'$\log(\frac{-\nabla_{r} P_{\rm mag}}{\rho g_{r}})$',
                        'units':'dimensionless',
                        'vmin':1e-5,
                        'vmax':+100,
                        'bin_min':1e-6,
                        'bin_max':+1,
                        'vmin_galaxy':1e-3,
                        'vmax_galaxy':+10,

    },
    grav_crpf = {'cmap':sns.color_palette("vlag", as_cmap=True),
                        'text_over':'black',
                        'label':r'$\frac{\vert \nabla P_{\rm CR}\vert}{\rho \vert g\vert}$',
                        'label_log':r'$\log(\frac{\vert \nabla P_{\rm CR}\vert}{\rho \vert g\vert})$',
                        'units':'dimensionless',
                        'vmin':1e-2,
                        'vmax':+10,
                        'bin_min':1e-2,
                        'bin_max':+10,
                        'vmin_galaxy':1e-2,
                        'vmax_galaxy':+1e+1

    },
        grav_gz = {'cmap':sns.color_palette("vlag", as_cmap=True),
                        'text_over':'black',
                        'label':r'$g_{z}$',
                        'label_log':r'$\log(\frac{g_{z}}{{\rm cm/s}^2})$',
                        'units':'cm/s**2',
                        'vmin':-100,
                        'vmax':+100,
                        'bin_min':-100,
                        'bin_max':+100,
                        'vmin_galaxy':-2e-9,
                        'vmax_galaxy':+2e-9,
                        'linthresh':1,
                        'linscale':1
    },
    grav_frsphere = {'cmap':sns.color_palette("vlag", as_cmap=True),
                        'text_over':'black',
                        'label':r'$\rho g_{r}$',
                        'label_log':r'$\log(\frac{\rho g_{r}}{{\rm g cm/s}^2})$',
                        'units':'g*cm/s**2',
                        'vmin':-100,
                        'vmax':+100,
                        'bin_min':-100,
                        'bin_max':+100,
                        'vmin_galaxy':-2e-32,
                        'vmax_galaxy':2e-32,
                        'linthresh':100,
                        'linscale':1

    },
    xHII = {'cmap':'bone',
            'text_over':'white',
            'label':r'$X_{\rm HII}$',
            'label_log':r'$\log(X_{\rm HII})$',
            'units':'dimensionless',
            'vmin':5e-4,
            'vmax':0.8,
            'vmin_galaxy':5e-4,
            'vmax_galaxy':0.8,
            'bin_min':1e-5,
            'bin_max':0.999

    },
    xHeII = {'cmap':'swift.red',
            'text_over':'white',
            'label':r'$X_{\rm HeII}$',
            'label_log':r'$\log(X_{\rm HeII})$',
            'units':'dimensionless',
            'vmin':5e-4,
            'vmax':0.8,
            'vmin_galaxy':5e-4,
            'vmax_galaxy':0.8,
            'bin_min':1e-5,
            'bin_max':0.999

    },
    xHeIII = {'cmap':'swift.red',
                'text_over':'white',
                'label':r'$X_{\rm HeIII}$',
                'label_log':r'$\log(X_{\rm HeIII})$',
                'units':'dimensionless',
                'vmin':5e-4,
                'vmax':0.8,
                'bin_min':1e-5,
                'bin_max':0.999

    },
    r_sphere = {'cmap': 'cividis',
                'text_over':'white',
                'label':r'$r$ [kpc]',
                'label_log':r'$\log\left(\frac{r}{kpc}\right)$',
                'units':'kpc',
                'vmin':0,
                'vmax':100,
                'vmin_galaxy':0,
                'vmax_galaxy':20
    },
    v_sphere_r = {'cmap':sns.color_palette("icefire", as_cmap=True),
                  'cmap_inflow':'GnBu_r',
                  'cmap_outflow':'YlOrBr_r',
                    'text_over':'white',
                    'label':r'$v_r$ [km/s]',
                    'label_log':r'$\log(\frac{v_r}{\rm km/s})$',
                    'units':'km*s**-1',
                    'vmin':-180,
                    'vmax':+210,
                    'bin_min':-400,
                    'bin_max':+400,
                    'vmin_galaxy':-200,
                    'vmax_galaxy':+250,
                    'vmin_outflow':15,
                    'vmax_outflow':300,
                    'vmin_inflow':80,
                    'vmax_inflow':20,
                    'vmin_cgm':-180,
                    'vmax_cgm':+210,
                    'linthresh':50,
                    'linscale':1
    },
    v_cyl_z = {'cmap':sns.color_palette("vlag", as_cmap=True),
                    'text_over':'black',
                    'label':r'$v_z$ [km/s]',
                    'label_log':r'$\log(\frac{v_z}{\rm km/s})$',
                    'units':'km*s**-1',
                    'vmin':-90,
                    'vmax':+90,
                    'bin_min':-90,
                    'bin_max':+90,
                    'vmin_galaxy':-90,
                    'vmax_galaxy':+90,
                    'linthresh':10,
                    'linscale':10
    },
    momentum_sphere_r = {'cmap':sns.color_palette("vlag", as_cmap=True),
                    'text_over':'black',
                    'label':r'$p_r$ [M$_{\odot}$ km/s]',
                    'units':'Msun*km*s**-1',
                    'bin_min':-1e+7,
                    'bin_max':1e+7,
                    'linthresh':10,
                    'linscale':1
    },
    absmomentum_sphere_r = {'cmap':sns.color_palette("vlag", as_cmap=True),
                    'text_over':'black',
                    'label':r'$\vert p_r\vert$ [M$_{\odot}$ km/s]',
                    'units':'Msun*km*s**-1',
                    'bin_min':0,
                    'bin_max':1e+7,
                    'linthresh':10,
                    'linscale':10
    },
    ang_momentum_x = {'cmap':sns.color_palette("vlag", as_cmap=True),
                    'text_over':'black',
                    'label':r'$L_x$ [M$_{\odot}$ kpc$\cdot$km/s]',
                    'units':'Msun*kpc*km*s**-1',
                    'bin_min':-1e+7,
                    'bin_max':1e+7,
                    'linthresh':10,
                    'linscale':10
    },
    ang_momentum_y = {'cmap':sns.color_palette("vlag", as_cmap=True),
                    'text_over':'black',
                    'label':r'$L_y$ [M$_{\odot}$ kpc$\cdot$km/s]',
                    'units':'Msun*kpc*km*s**-1',
                    'bin_min':-1e+7,
                    'bin_max':1e+7,
                    'linthresh':10,
                    'linscale':10
    },
    ang_momentum_z = {'cmap':sns.color_palette("vlag", as_cmap=True),
                    'text_over':'black',
                    'label':r'$L_z$ [M$_{\odot}$ kpc$\cdot$km/s]',
                    'units':'Msun*kpc*km*s**-1',
                    'bin_min':-1e+7,
                    'bin_max':1e+7,
                    'linthresh':10,
                    'linscale':10
    },
    ang_momentum = {'cmap':sns.color_palette("vlag", as_cmap=True),
                    'text_over':'black',
                    'label':r'$L$ [M$_{\odot}$ kpc$\cdot$km/s]',
                    'label_log':r'$L$ [M$_{\odot}$ kpc$\cdot$km/s]',
                    'units':'Msun*kpc*km*s**-1',
                    'bin_min':1e-2,
                    'bin_max':1e+7,
                    'vmin_cgm':1e-2,
                    'vmax_cgm':1e5  
    },
    ang_momentum_specific = {'cmap':sns.color_palette("vlag", as_cmap=True),
                                'text_over':'black',
                                'label':r'$L$ [kpc$\cdot$km/s]',
                                'label_log':r'$L$ [kpc$\cdot$km/s]',
                                'units':'kpc*km*s**-1',
                                'bin_min':1e1,
                                'bin_max':1e7,
                                'vmin_cgm':3e1,
                                'vmax_cgm':8e3  
    },
    massflow_rate = {'cmap':sns.color_palette("vlag", as_cmap=True),
                                'text_over':'black',
                                'label':r'$dM/dt$ [M$_{\odot}$ yr$^{-1}$]',
                                'units':'Msun*yr**-1',
                                'bin_min':-100,
                                'bin_max':100
    },
    massflow_rate_sphere_r = {'cmap': sns.color_palette("icefire", as_cmap=True),
                                'text_over':'white',
                                'label':r'$dM/dt$ [M$_{\odot}$ yr$^{-1}$]',
                                'units':'Msun*yr**-1',
                                'bin_min':-100,
                                'bin_max':100,
                                'vmin_cgm':-5e-3,
                                'vmax_cgm':5e-3,
                                'linthresh':1e-3,
                                'linscale':1e-3
    },
    sigma = {'cmap':'swift.red',
                        'text_over':'white',
                        'label':r'$\sigma_{\rm turb}$ [km s$^{-1}$]',
                        'label_log':r'$\log(\frac{\sigma_{\rm turb}}{{\rm km s}^{-1}})$',
                        'units':'km/s',
                        'vmin':1e-1,
                        'vmax':200,
                        'bin_min':1e-2,
                        'bin_max':1e3,
                        'vmin_galaxy':2,
                        'vmax_galaxy':80,
                        'vmin_cgm':2,
                        'vmax_cgm':80

    },
    mach_number = {'cmap':'twilight_shifted',
                        'text_over':'white',
                        'label':r'$\mathcal{M}$]',
                        'label_log':r'$\log(\mathcal{M})$',
                        'units':'dimensionless',
                        'vmin':0.1,
                        'vmax':200,
                        'bin_min':0.01,
                        'bin_max':1e3,
                        'vmin_galaxy':0.01,
                        'vmax_galaxy':100,
                        'vmin_cgm':0.1,
                        'vmax_cgm':200

    },
    star_mass = {'cmap':'gray',
                'text_over':'white',
                'label':r'$M_{*}$ [M$_{\odot}$]',
                'label_log':r'$\log\left(\frac{M_{*}}{{\rmM}_{\odot}}\right)$',
                'units':'Msun',
                'vmin':5.0,
                'vmax':2e+7,
                'vmin_galaxy':5.0,
                'vmax_galaxy':2e+7
    },
    star_sdensity = {'cmap':'gray',
                        'text_over':'white',
                        'label':r'$\Sigma_{*}$ [M$_{\odot}$ kpc$^{-2}$]',
                        'label_log':r'$\log\left(\frac{\Sigma_{*}}{{\rm M}_{\odot}{\rm kpc}^{-2}}\right)$',
                        'units':'Msun/(kpc**2)',
                        'vmin':3e+4,
                        'vmax':5e+9,
                        'vmin_galaxy':3e+3,
                        'vmax_galaxy':5e+9,
                        'vmin_cgm':3e+1,
                        'vmax_cgm':5e+3,

    },
    dm_sdensity = {'cmap':'cividis',
                        'text_over':'white',
                        'label':r'$\Sigma_{\rm DM}$ [M$_{\odot}$ kpc$^{-2}$]',
                        'label_log':r'$\log\left(\frac{\Sigma_{\rm DM}}{{\rm M}_{\odot}{\rm kpc}^{-2}}\right)$',
                        'units':'Msun/(kpc**2)',
                        'vmin':4e+7,
                        'vmax':3e+9,
                        'vmin_galaxy':8e+6,
                        'vmax_galaxy':7e+8,
                        'vmin_cluster':4e+5,
                        'vmax_cluster':3e+8,
                        'vmin_cgm':4e+3,
                        'vmax_cgm':3e+6

    },
    dm_mass = {'cmap':'cividis',
                'text_over':'white',
                'label':r'$M_{DM}$ [M$_{\odot}$]',
                'label_log':r'$\log\left(\frac{M_{\rm DM}}{{\rmM}_{\odot}}\right)$',
                'units':'Msun',
                'vmin':3.0e+3,
                'vmax':7e+6,
                'vmin_galaxy':3.0e+3,
                'vmax_galaxy':7e+6
    },
    star_metallicity = {'cmap':sns.color_palette("dark:salmon", as_cmap=True),
                        'text_over':'white',
                        'label':r'$Z$ [$Z_{\odot}$]',
                        'units':'dimensionless',
                        'vmin':1e-1,
                        'vmax':None
    },
    star_age = {'cmap':'BuPu',
                'text_over':'white',
                'label':r'Age [Gyr]',
                'units':'Gyr',
                'vmin':None,
                'vmax':None
    },
    star_sfr_surface_100 = {'cmap':'magma',
                            'text_over':'white',
                            'label':r'$\langle \Sigma_{\rm SFR}\rangle)_{\rm 100 Myr})$ [M$_{\odot}$ yr$^{-1}$ kpc$^{-2}$]',
                            'label_log':r'$\log\left(\frac{ \langle\Sigma_{\rm SFR}\rangle _{\rm 100 Myr}}{{\rm M}_{\odot}{\rm yr}^{-1}{\rm kpc}^{-2}}\right)$',
                            'units':'Msun/(yr*kpc**2)',
                            'vmin':3e-4,
                            'vmax':90,
                            'vmin_galaxy':3e-4,
                            'vmax_galaxy':90
    },
    DTM = {'cmap': sns.color_palette("icefire", as_cmap=True),
                'text_over':'white',
                'label':r'DTM',
                'label_log':r'$\log\left(\rm DTM\right)$',
                'units':'dimensionless',
                'vmin':0,
                'vmax':0.3,
                'vmin_isolated':0.1,
                'vmax_isolated':0.3,
                'vmin_galaxy':8e-3,
                'vmax_galaxy':0.2
    },
    dust_density = {'cmap': sns.color_palette("icefire", as_cmap=True),
                'text_over':'black',
                'label':r'$\rho_{\rm dust}$ [g/cm$^{3}$]',
                'label_log':r'$\log\left(\frac{\rho_{\rm dust}}{{\rm g cm}^{-3}}\right)$',
                'units':'dimensionless',
                'vmin':2e-34,
                'vmax':7e-30,
                'vmin_galaxy':2e-33,
                'vmax_galaxy':5e-30,
    },
    eff_FKmag = {'cmap':'magma',
                'text_over':'white',
                'label':r'$\epsilon_{\rm ff}^{\rm MTT}$',
                'label_log':r'$\log{\epsilon_{\rm ff}^{\rm MTT}}$',
                'units':'dimensionless',
                'vmin':1e-4,
                'vmax':0.01,
                'vmin_galaxy':1e-4,
                'vmax_galaxy':0.01,
                'bin_min':1e-5,
                'bin_max':10
    },
    eff_FKmagnocr = {'cmap':'magma',
                'text_over':'white',
                'label':r'$\epsilon_{\rm ff}^{\rm MTT}$',
                'label_log':r'$\log{\epsilon_{\rm ff}^{\rm MTT}}$',
                'units':'dimensionless',
                'vmin':1e-4,
                'vmax':0.01,
                'vmin_galaxy':1e-4,
                'vmax_galaxy':0.01,
                'bin_min':1e-5,
                'bin_max':10
    },
    eff_FK2 = {'cmap':'magma',
                'text_over':'white',
                'label':r'$\epsilon_{\rm ff}^{\rm MTT}$',
                'label_log':r'$\log{\epsilon_{\rm ff}^{\rm MTT}}$',
                'units':'dimensionless',
                'vmin':1e-4,
                'vmax':0.01,
                'vmin_galaxy':1e-4,
                'vmax_galaxy':0.01,
                'bin_min':1e-5,
                'bin_max':10
    },
    neighbour_accuracy = {'cmap':'magma',
                'text_over':'white',
                'label':'Neighbour Accuracy',
                'label_log':'Neighbour Accuracy',
                'units':'dimensionless',
                'vmin':0.9,
                'vmax':1,
                'vmin_galaxy':0.9,
                'vmax_galaxy':1
    }
)

circle_dictionary = dict(
        rvir_halo = {'edgecolor': 'r',
                        'linestyle':'--',
                        'linewidth':2.0
        },
        rvir_galaxy = {'edgecolor': 'y',
                        'linestyle':'--',
                        'linewidth':1.0
        },
        rvir_satellite = {'edgecolor': 'w',
                          'linestyle':'--',
                        'linewidth':1.0
        },
        tidal_BT87_simple = {'edgecolor': 'r',
                          'linestyle':':',
                        'linewidth':1.0
        },
        tidal_BT87_centrifugal = {'edgecolor': 'b',
                          'linestyle':':',
                        'linewidth':1.0
        }
)