import matplotlib.pyplot as plt
import swiftascmaps
import seaborn as sns
sns.set(style="white")

symlog_variables = [
    'v_sphere_r',
    'v_cyl_z',
    'grav_crpfz',
    'grav_therpfz',
    'grav_crpfrsphere',
    'grad_crpz',
    'grav_gz'
]

plotting_dictionary = dict(
    density = {'cmap': sns.color_palette("mako", as_cmap=True),
                'text_over':'white',
                'label':r'$\rho$ [g/cm$^{-3}$]',
                'label_log':r'$\log\left(\frac{\rho}{{\rm g cm}^{-3}}\right)$',
                'units':'g*cm**-3',
                'vmin':2e-32,
                'vmax':7e-20,
                'vmin_galaxy':2e-28,
                'vmax_galaxy':5e-22,
    },
    mass = {'cmap':sns.color_palette("mako", as_cmap=True),
            'text_over':'white',
            'label':r'Mass [M$_{\odot}$]',
            'label_log':r'$\log$(\frac{Mass}{{\rmM}$_{\odot}$})',
            'units':'Msun',
            'vmin':1,
            'vmax':1e+8,
            'vmin_galaxy':1e+3,
            'vmax_galaxy':1e+8
    },
    temperature = {'cmap':sns.color_palette("rocket", as_cmap=True),
                    'text_over':'white',
                    'label':r'$T$ [K]',
                    'label_log':r'$\log\left(\frac{T}{{\rm K}}\right)$',
                    'units':'K',
                    'vmin':8,
                    'vmax':8e+8,
                    'vmin_galaxy':8e+1,
                    'vmax_galaxy':8e+6,
                    'vmin_outflow':5e+3,
                    'vmax_outflow':3e+5
    },
    thermal_energy = {'cmap':sns.color_palette("rocket", as_cmap=True),
                            'text_over':'white',
                            'label':r'$E_{\rm ther}$ [erg]',
                            'label_log':r'$\log(\frac{E_{\rm ther}}{{\rm erg}})$',
                            'units':'erg',
                            'vmin':5e+1,
                            'vmax':2e+6,
                            'vmin_galaxy':5e+3,
                            'vmax_galaxy':8e+6
    },
    thermal_pressure = {'cmap':'viridis',
                            'text_over':'white',
                            'label':r'$P_{\rm ther}$ [erg/cm$^{-3}$]',
                            'label_log':r'$\log\left(\frac{P_{\rm ther}}{{\rm erg/cm}^{-3}}\right)$',
                            'units':'erg*cm**-3',
                            'vmin':3e-15,
                            'vmax':8e-9,
                            'vmin_galaxy':3e-15,
                            'vmax_galaxy':8e-9
    },
    thermal_energy_specific = {'cmap':sns.color_palette("rocket", as_cmap=True),
                                'text_over':'white',
                                'label':r'$\epsilon_{\rm ther}$ [erg/g]',
                                'label_log':r'$\log(\frac{\epsilon_{\rm ther}}{{\rm erg/g}})$',
                                'units':'erg*g**-1',
                                'vmin':5e+1,
                                'vmax':2e+6,
                                'vmin_galaxy':5e+3,
                                'vmax_galaxy':8e+6
    },
    net_cooling = {'cmap':'vlag',
                        'text_over':'black',
                        'label':r'$\Lambda_{\rm cool}$ [erg/(s cm$^{3}$)]',
                        'label_log':r'$\log(\frac{\Lambda_{\rm cool}}{{\rm erg/(s cm}^{3})}})$',
                        'units':'erg*s**-1*cm**-3',
                        'vmin':-1e-18,
                        'vmax':1e-10,
                        'vmin_galaxy':1e-35,
                        'vmax_galaxy':1e-23,
                        'linthresh':1,
                        'linscale':1
    },
    entropy_specific = {'cmap':'plasma',
                        'text_over':'white',
                        'label':r'$s$ [erg/(g K)]',
                        'label_log':r'$\log(\frac{s}{{\rm erg/(g K)}})$',
                        'units':'erg*K**-1*g**-1',
                        'vmin':8e+3,
                        'vmax':2e+5,
                        'vmin_galaxy':8e+7,
                        'vmax_galaxy':2e+9
    },
    metallicity = {'cmap':'swift.nineteen_eighty_nine',
                    'text_over':'black',
                    'label':r'$Z$ [$Z_{\odot}$]',
                    'label_log':r'$\log\left(Z/Z_{\odot}\right)$',
                    'units':'dimensionless',
                    'vmin':5e-3,
                    'vmax':1.5,
                    'vmin_galaxy':5e-3,
                    'vmax_galaxy':1.5
    },
    magnetic_energy = {'cmap':sns.cubehelix_palette(reverse=True,as_cmap=True),
                                'text_over':'white',
                                'label':r'$E_{\rm mag}$ [erg]',
                                'label_log':r'$\log(\frac{E_{\rm mag}}{{\rm erg}})$',
                                'units':'erg',
                                'vmin':5e+10,
                                'vmax':3e+12

    },
    magnetic_energy_specific = {'cmap':sns.cubehelix_palette(reverse=True,as_cmap=True),
                                'text_over':'white',
                                'label':r'$\epsilon_{\rm mag}$ [erg/g]',
                                'units':'erg*g**-1',
                                'vmin':5e+8,
                                'vmax':3e+11,
                                'vmin_galaxy':5e+8,
                                'vmax_galaxy':3e+11

    },
    magnetic_energy_density = {'cmap':sns.cubehelix_palette(reverse=True,as_cmap=True),
                                'text_over':'white',
                                'label':r'$\varepsilon_{\rm mag}$ [erg/cm$^{3}$]',
                                'label_log':r'$\log(\frac{\varepsilon_{\rm mag}}{{\rm erg/cm}^{3}})$',
                                'units':'erg*cm**-3',
                                'vmin':4e-17,
                                'vmax':5e-11,
                                'vmin_galaxy':4e-17,
                                'vmax_galaxy':5e-11

    },
    magnetic_magnitude = {'cmap':'inferno',
                                'text_over':'white',
                                'label':r'$B$ [$G$]',
                                'label_log':r'$\log(\frac{B}{{\rm G}})$',
                                'units':'G',
                                'vmin':4e-17,
                                'vmax':5e-11,
                                'vmin_galaxy':4e-10,
                                'vmax_galaxy':5e-5

    },
    alfven_speed = {'cmap':'swift.red',
                                'text_over':'white',
                                'label':r'$v_A$ [km s$^{-1}$]',
                                'label_log':r'$\log(\frac{v_A}{{\rm km s}^{-1}})$',
                                'units':'km/s',
                                'vmin':3e-2,
                                'vmax':5e0,
                                'vmin_galaxy':3e-2,
                                'vmax_galaxy':5e0

    },
    total_crs_energy = {'cmap':sns.cubehelix_palette(start=2, rot=0, dark=0, light=.95, reverse=True, as_cmap=True),
                        'text_over':'white',
                        'label':r'$E_{\rm CR}$ [erg]',
                        'label_log':r'$\log(\frac{\varepsilon_{\rm CR}}{{\rm erg/cm}^{3}})$',
                        'label_log':r'$\log(\frac{E_{\rm CR}}{{\rm erg}})$',
                        'units':'erg',
                        'vmin':4e-14,
                        'vmax':8e-11,
                        'vmin_galaxy':4e-14,
                        'vmax_galaxy':8e-11

    },
    cr_energy_density = {'cmap':'YlGnBu_r',#sns.cubehelix_palette(start=2, rot=0, dark=0, light=.95, reverse=False, as_cmap=True),
                        'text_over':'black',
                        'label':r'$\varepsilon_{\rm CR}$ [erg/cm$^{3}$]',
                        'label_log':r'$\log(\frac{\varepsilon_{\rm CR}}{{\rm erg/cm}^{3}})$',
                        'units':'erg*cm**-3',
                        'vmin':7e-18,
                        'vmax':8e-12,
                        'vmin_galaxy':6e-14,
                        'vmax_galaxy':2e-10

    },
    cr_temperature_eff = {'cmap':'YlGnBu_r',#sns.cubehelix_palette(start=2, rot=0, dark=0, light=.95, reverse=False, as_cmap=True),
                        'text_over':'black',
                        'label':r'$T_{\rm CR,eff}$ [erg/cm$^{3}$]',
                        'label_log':r'$\log\left(\frac{T_{\rm CR,eff}}{{\rm K}}\right)$',
                        'units':'K',
                        'vmin':2e+4,
                        'vmax':8e+6,
                        'vmin_galaxy':8e+1,
                        'vmax_galaxy':8e+6,
                        'vmin_outflow':5e+3,
                        'vmax_outflow':3e+5

    },
    cr_pressure = {'cmap':'YlGnBu_r',#sns.cubehelix_palette(start=2, rot=0, dark=0, light=.95, reverse=False, as_cmap=True),
                        'text_over':'black',
                        'label':r'$P_{\rm CR}$ [erg/cm$^{3}$]',
                        'label_log':r'$\log(\frac{P_{\rm CR}}{{\rm erg/cm}^{3}})$',
                        'units':'erg*cm**-3',
                        'vmin':7e-18,
                        'vmax':8e-12,
                        'vmin_grad':7e-16,
                        'vmax_grad':8e-13,
                        'vmin_galaxy':6e-14,
                        'vmax_galaxy':2e-10

    },
    grad_crp = {'cmap':'YlGnBu_r',#sns.cubehelix_palette(start=2, rot=0, dark=0, light=.95, reverse=False, as_cmap=True),
                        'text_over':'white',
                        'label':r'$\vert \nabla P_{\rm CR}\vert$ [erg/cm$^{4}$]',
                        'label_log':r'$\log(\frac{\vert \nabla P_{\rm CR}\vert}{{\rm erg/cm}^{4}})$',
                        'units':'erg*cm**-4',
                        'vmin':6e-34,
                        'vmax':2e-31,
                        'vmin_galaxy':6e-34,
                        'vmax_galaxy':2e-31

    },
    grad_crpz = {'cmap':sns.color_palette("vlag", as_cmap=True),
                        'text_over':'black',
                        'label':r'$\nabla_z P_{\rm CR}$ [erg/cm$^{4}$]',
                        'label_log':r'$\log(\frac{\nabla_z P_{\rm CR}}{{\rm erg/cm}^{4}})$',
                        'units':'erg*cm**-4',
                        'vmin':-2e-31,
                        'vmax':2e-31,
                        'vmin_galaxy':-2e-28,
                        'vmax_galaxy':2e-28

    },
    streaming_heating = {'cmap':'gnuplot',
                        'text_over':'white',
                        'label':r'$\Lambda_{\rm st}$ [erg/(s cm$^{3})$]',
                        'label_log':r'$\log(\frac{\Lambda_{\rm st}}{{\rm erg/(s cm}^{3})})$',
                        'units':'erg*s**-1*cm**-3',
                        'vmin':3e-33,
                        'vmax':1e-23,
                        'vmin_galaxy':3e-33, 
                        'vmax_galaxy':1e-23,

    },
    cr_energy_specific = {'cmap':sns.cubehelix_palette(start=.5, rot=-.75, as_cmap=True), #sns.cubehelix_palette(start=2, rot=0, dark=0, light=.95, reverse=True, as_cmap=True),
                                'text_over':'white',
                                'label':r'$\epsilon_{\rm CR}$ [erg/g]',
                                'label_log':r'$\log(\frac{\epsilon_{\rm CR}}{\rm erg/g})$',
                                'units':'erg*g**-1',
                                'vmin':5e+12,
                                'vmax':7e+14,
                                'vmin_galaxy':5e+10,
                                'vmax_galaxy':7e+15

    },
    total_coolingtime = {'cmap':'swift.red',
                                'text_over':'white',
                                'label':r'$t_{\rm cool}$ [Myr]',
                                'label_log':r'$\log(\frac{t_{\rm cool}}{\rm Myr})$',
                                'units':'Myr',
                                'vmin':1e+1,
                                'vmax':7e+5,
                                'vmin_galaxy':1e+1,
                                'vmax_galaxy':7e+5

    },
    crthermal_ratio = {'cmap':sns.color_palette("vlag", as_cmap=True),
                        'text_over':'black',
                        'label':r'$\frac{\nabla P_{\rm CR}}{\nabla P_{\rm ther}}$',
                        'label_log':r'$\log(\frac{\nabla P_{\rm CR}}{\nabla P_{\rm ther}})$',
                        'units':'dimensionless',
                        'vmin':7e-18,
                        'vmax':8e-12,
                        'vmin_galaxy':1e-3,
                        'vmax_galaxy':1e+2

    },
    grav_crpfz = {'cmap':sns.color_palette("vlag", as_cmap=True),
                        'text_over':'black',
                        'label':r'$\frac{-\nabla_{z} P_{\rm CR}}{\rho g_{z}}$',
                        'label_log':r'$\log(\frac{-\nabla_{z} P_{\rm CR}}{\rho g_{z}})$',
                        'units':'dimensionless',
                        'vmin':-100,
                        'vmax':+100,
                        'vmin_galaxy':-5,
                        'vmax_galaxy':+5

    },
    grav_therpfz = {'cmap':sns.color_palette("vlag", as_cmap=True),
                        'text_over':'black',
                        'label':r'$\frac{-\nabla_{z} P_{\rm ther}}{\rho g_{z}}$',
                        'label_log':r'$\log(\frac{-\nabla_{z} P_{\rm ther}}{\rho g_{z}})$',
                        'units':'dimensionless',
                        'vmin':-100,
                        'vmax':+100,
                        'vmin_galaxy':-5,
                        'vmax_galaxy':+5

    },
    grav_crpfrsphere = {'cmap':sns.color_palette("vlag", as_cmap=True),
                        'text_over':'black',
                        'label':r'$\frac{-\nabla_{r} P_{\rm CR}}{\rho g_{r}}$',
                        'label_log':r'$\log(\frac{-\nabla_{r} P_{\rm CR}}{\rho g_{r}})$',
                        'units':'dimensionless',
                        'vmin':-100,
                        'vmax':+100,
                        'vmin_galaxy':-5,
                        'vmax_galaxy':+5,
                        'linthresh':1,
                        'linscale':10

    },
    grav_therpfrsphere = {'cmap':sns.color_palette("vlag", as_cmap=True),
                        'text_over':'black',
                        'label':r'$\frac{-\nabla_{r} P_{\rm ther}}{\rho g_{r}}$',
                        'label_log':r'$\log(\frac{-\nabla_{r} P_{\rm ther}}{\rho g_{r}})$',
                        'units':'dimensionless',
                        'vmin':-100,
                        'vmax':+100,
                        'vmin_galaxy':-5,
                        'vmax_galaxy':+5

    },
    grav_crpf = {'cmap':sns.color_palette("vlag", as_cmap=True),
                        'text_over':'black',
                        'label':r'$\frac{\vert \nabla P_{\rm CR}\vert}{\rho \vert g\vert}$',
                        'label_log':r'$\log(\frac{\vert \nabla P_{\rm CR}\vert}{\rho \vert g\vert})$',
                        'units':'dimensionless',
                        'vmin':0,
                        'vmax':+10,
                        'vmin_galaxy':1e-2,
                        'vmax_galaxy':+1e+1

    },
        grav_gz = {'cmap':sns.color_palette("vlag", as_cmap=True),
                        'text_over':'black',
                        'label':r'$g_{z}$',
                        'label_log':r'$\log(\frac{g_{z}}{{\rm cm/s}^2})$',
                        'units':'cm/s**2',
                        'vmin':-100,
                        'vmax':+100,
                        'vmin_galaxy':-2e-9,
                        'vmax_galaxy':+2e-9

    },
    xHII = {'cmap':'bone',
            'text_over':'white',
            'label':r'$X_{\rm HII}$',
            'label_log':r'$\log(X_{\rm HII})$',
            'units':'dimensionless',
            'vmin':5e-4,
            'vmax':0.8,
            'vmin_galaxy':5e-4,
            'vmax_galaxy':0.8

    },
    xHeII = {'cmap':'swift.red',
            'text_over':'white',
            'label':r'$X_{\rm HeII}$',
            'label_log':r'$\log(X_{\rm HeII})$',
            'units':'dimensionless',
            'vmin':5e-4,
            'vmax':0.8,
            'vmin_galaxy':5e-4,
            'vmax_galaxy':0.8

    },
    xHeIII = {'cmap':'swift.red',
                'text_over':'white',
                'label':r'$X_{\rm HeIII}$',
                'label_log':r'$\log(X_{\rm HeIII})$',
                'units':'dimensionless',
                'vmin':5e-4,
                'vmax':0.8

    },
    r_sphere = {'cmap': 'cividis',
                'text_over':'white',
                'label':r'$r$ [kpc]',
                'label_log':r'$\log\left(\frac{r}{kpc}\right)$',
                'units':'kpc',
                'vmin':0,
                'vmax':100,
                'vmin_galaxy':0,
                'vmax_galaxy':20
    },
    v_sphere_r = {'cmap':sns.color_palette("vlag", as_cmap=True),
                    'text_over':'black',
                    'label':r'$v_r$ [km/s]',
                    'label_log':r'$\log(\frac{v_r}{\rm km/s})$',
                    'units':'km*s**-1',
                    'vmin':-90,
                    'vmax':+90,
                    'vmin_galaxy':-90,
                    'vmax_galaxy':+90
    },
    v_cyl_z = {'cmap':sns.color_palette("vlag", as_cmap=True),
                    'text_over':'black',
                    'label':r'$v_z$ [km/s]',
                    'label_log':r'$\log(\frac{v_z}{\rm km/s})$',
                    'units':'km*s**-1',
                    'vmin':-90,
                    'vmax':+90,
                    'vmin_galaxy':-90,
                    'vmax_galaxy':+90
    },
    momentum_sphere_r = {'cmap':sns.color_palette("vlag", as_cmap=True),
                    'text_over':'black',
                    'label':r'$p_r$ [M$_{\odot}$ km/s]',
                    'units':'Msun*km*s**-1'
    },
    massflow_rate = {'cmap':sns.color_palette("vlag", as_cmap=True),
                                'text_over':'black',
                                'label':r'$dM/dt$ [M$_{\odot}$ yr$^{-1}$]',
                                'units':'Msun*yr**-1'
    },
    massflow_rate_sphere_r = {'cmap':sns.color_palette("vlag", as_cmap=True),
                                'text_over':'black',
                                'label':r'$dM/dt$ [M$_{\odot}$ yr$^{-1}$]',
                                'units':'Msun*yr**-1'
    },
    star_mass = {'cmap':'gray',
                'text_over':'white',
                'label':r'$M_{*}$ [M$_{\odot}$]',
                'label_log':r'$\log\left(\frac{M_{*}}{{\rmM}_{\odot}}\right)$',
                'units':'Msun',
                'vmin':5.0,
                'vmax':2e+7,
                'vmin_galaxy':5.0,
                'vmax_galaxy':2e+7
    },
    star_sdensity = {'cmap':'gray',
                        'text_over':'white',
                        'label':r'$\Sigma_{*}$ [M$_{\odot}$ kpc$^{-2}$]',
                        'label_log':r'$\log\left(\frac{\Sigma_{*}}{{\rmM}_{\odot}{\rm kpc}^{-2}}\right)$',
                        'units':'Msun/(kpc**2)',
                        'vmin':3e+4,
                        'vmax':5e+9,
                        'vmin_galaxy':3e+4,
                        'vmax_galaxy':5e+9

    },
    dm_sdensity = {'cmap':'cividis',
                        'text_over':'white',
                        'label':r'$\Sigma_{\rm DM}$ [M$_{\odot}$ kpc$^{-2}$]',
                        'label_log':r'$\log\left(\frac{\Sigma_{\rm DM}}{{\rmM}_{\odot}{\rm kpc}^{-2}}\right)$',
                        'units':'Msun/(kpc**2)',
                        'vmin':4e+7,
                        'vmax':3e+9,
                        'vmin_galaxy':4e+7,
                        'vmax_galaxy':3e+9

    },
    dm_mass = {'cmap':'cividis',
                'text_over':'white',
                'label':r'$M_{DM}$ [M$_{\odot}$]',
                'label_log':r'$\log\left(\frac{M_{\rm DM}}{{\rmM}_{\odot}}\right)$',
                'units':'Msun',
                'vmin':3.0e+3,
                'vmax':7e+6,
                'vmin_galaxy':3.0e+3,
                'vmax_galaxy':7e+6
    },
    star_metallicity = {'cmap':sns.color_palette("dark:salmon", as_cmap=True),
                        'text_over':'white',
                        'label':r'$Z$ [$Z_{\odot}$]',
                        'units':'dimensionless',
                        'vmin':1e-1,
                        'vmax':None
    },
    star_age = {'cmap':'BuPu',
                'text_over':'white',
                'label':r'Age [Gyr]',
                'units':'Gyr',
                'vmin':None,
                'vmax':None
    },
    star_sfr_surface_100 = {'cmap':'magma',
                            'text_over':'white',
                            'label':r'$\Sigma_{\rm SFR}$ [M$_{\odot}$ yr$^{-1}$ kpc$^{-2}$]',
                            'label_log':r'$\log\left(\frac{\Sigma_{\rm SFR}}{{\rmM}_{\odot}{\rm yr}^{-1}{\rm kpc}^{-2}}\right)$',
                            'units':'Msun/(yr*kpc**2)',
                            'vmin':3e-4,
                            'vmax':90,
                            'vmin_galaxy':3e-4,
                            'vmax_galaxy':90
    }
)

circle_dictionary = dict(
        rvir_galaxy = {'edgecolor': 'y',
                        'linestyle':'--'
        },
        rvir_satellite = {'edgecolor': 'w',
                          'linestyle':'--'
        },
        tidal_BT87_simple = {'edgecolor': 'r',
                          'linestyle':':'
        },
        tidal_BT87_centrifugal = {'edgecolor': 'b',
                          'linestyle':':'
        }
)